export const mealContants = {
  GET_MEALS: "GET_MEALS",

  ADD_MEAL_REQUEST: "ADD_MEAL_REQUEST",
  ADD_MEAL_SUCCESS: "ADD_MEAL_SUCCESS",
  ADD_MEAL_FAILURE: "ADD_MEAL_FAILURE",

  GET_MEAL_BY_ID: "GET_MEAL_BY_ID",

  DELETE_MEAL_BY_ID_REQUEST: "DELETE_MEAL_BY_ID_REQUEST",
  DELETE_MEAL_BY_ID_SUCCESS: "DELETE_MEAL_BY_ID_SUCCESS",
  DELETE_MEAL_BY_ID_FAILURE: "DELETE_MEAL_BY_ID_FAILURE",

  UPDATE_MEAL_BY_ID_REQUEST: "UPDATE_MEAL_BY_ID_REQUEST",
  UPDATE_MEAL_BY_ID_SUCCESS: "UPDATE_MEAL_BY_ID_SUCCESS",
  UPDATE_MEAL_BY_ID_FAILURE: "UPDATE_MEAL_BY_ID_FAILURE",
};

export const tableContants = {
  GET_TABLES: "GET_TABLES",

  ADD_TABLE_REQUEST: "ADD_TABLE_REQUEST",
  ADD_TABLE_SUCCESS: "ADD_TABLE_SUCCESS",
  ADD_TABLE_FAILURE: "ADD_TABLE_FAILURE",

  GET_TABLE_BY_ID: "GET_MEAL_BY_ID",

  BOOK_TABLE: "BOOK_TABLE",

  DELETE_TABLE_BY_ID_REQUEST: "DELETE_TABLE_BY_ID_REQUEST",
  DELETE_TABLE_BY_ID_SUCCESS: "DELETE_TABLE_BY_ID_SUCCESS",
  DELETE_TABLE_BY_ID_FAILURE: "DELETE_TABLE_BY_ID_FAILURE",

  UPDATE_TABLE_BY_ID_REQUEST: "UPDATE_TABLE_BY_ID_REQUEST",
  UPDATE_TABLE_BY_ID_SUCCESS: "UPDATE_TABLE_BY_ID_SUCCESS",
  UPDATE_TABLE_BY_ID_FAILURE: "UPDATE_TABLE_BY_ID_FAILURE",

  ADD_MEAL_TO_TABLE_REQUEST: "ADD_MEAL_TO_TABLE_REQUEST",
  ADD_MEAL_TO_TABLE_SUCCESS: "ADD_MEAL_TO_TABLE_SUCCESS",
  ADD_MEAL_TO_TABLE_FAILURE: "ADD_MEAL_TO_TABLE_FAILURE",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  CHANGE_INFO_REQUEST: "CHANGE_INFO_REQUEST",
  CHANGE_INFO_SUCCESS: "CHANGE_INFO_SUCCESS",
  CHANGE_INFO_FAILURE: "CHANGE_INFO_FAILURE",
};

export const cartContants = {
  ADD_MEAL_TO_CART: "ADD_MEAL_TO_CART",

  CLEAR_CART: "CLEAR_CART",
};

export const orderContants = {
  GET_ORDERS: "GET_ORDERS",
  ADD_ORDER: "ADD_ORDER",

  GET_ORDER_BY_ID: "GET_ORDER_BY_ID",
};

export const categoryContants = {
  GET_CATEGORIES: "GET_CATEGORIES",

  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
};

export const ingredientTypeContants = {
  GET_INGREDIENT_TYPE: "GET_INGREDIENT_TYPE",

  ADD_INGREDIENT_TYPE_REQUEST: "ADD_INGREDIENT_TYPE_REQUEST",
  ADD_INGREDIENT_TYPE_SUCCESS: "ADD_INGREDIENT_TYPE_SUCCESS",
  ADD_INGREDIENT_TYPE_FAILURE: "ADD_INGREDIENT_TYPE_FAILURE",
};

export const ingredientContants = {
  GET_INGREDIENTS: "GET_INGREDIENTS",
};
