const url = 'http://localhost:3000/api';
export const API_ENDPOINTS = {
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  FORGET_PASSWORD: '/forget-password',
  CATEGORIES: url + '/categories.json',
  DIETARY: url + '/dietary.json',
  BRANDS: url + '/brands.json',
  PRODUCTS: url + '/products.json',
  PRODUCT: url + '/product.json',
  RELATED_PRODUCTS: url + '/related_products.json',
  BEST_SELLER_PRODUCTS: url + '/products_best_seller.json',
  BEST_SELLER_GROCERY_PRODUCTS: url + '/products_best_seller_grocery.json',
  POPULAR_PRODUCTS: url + '/products_popular.json',
  COOKIES_PRODUCTS: url + '/products_cookies.json',
  CHIPS_PRODUCTS: url + '/products_chips.json',
  POPCORN_JERKY_PRODUCTS: url + '/products_popcorn_jerky.json',
  FRESH_VEGETABLES_PRODUCTS: url + '/products_fresh_vegetables.json',
  SEARCH: url + '/search.json',
  ORDERS: url + '/orders.json',
  ORDER: url + '/order.json',
  ORDER_STATUS: url + '/order-status.json',
  ADDRESS: url + '/address.json',
  PAYMENT: url + '/payment.json',
  CONTACT: url + '/contact.json',
  SHOP: url + '/shop.json',
  SHOPS: url + '/shops.json',
  WISHLIST: url + '/wishlist.json',
};
